#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Pose
from std_msgs.msg import Int8

R = 0x43
L = 0x44
U = 0x41
D = 0x42

def gpsCallback(data):
    pass

def main():
    rospy.init_node("path_follower")

    gps_sub = rospy.Subscriber("gps_msgs", Pose, gpsCallback)

    throttle_pub = rospy.Publisher("throttle_msgs", Int8, queue_size=1000)

    while not rospy.is_shutdown():
        throttle_pub.publish(U)

if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
