// Generated by gencpp from file common_msgs/ConeMap.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_CONEMAP_H
#define COMMON_MSGS_MESSAGE_CONEMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <common_msgs/Cone.h>
#include <common_msgs/Cone.h>
#include <common_msgs/Cone.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct ConeMap_
{
  typedef ConeMap_<ContainerAllocator> Type;

  ConeMap_()
    : header()
    , blue_cones()
    , yellow_cones()
    , orange_cones()  {
    }
  ConeMap_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , blue_cones(_alloc)
    , yellow_cones(_alloc)
    , orange_cones(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::common_msgs::Cone_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::common_msgs::Cone_<ContainerAllocator> >::other >  _blue_cones_type;
  _blue_cones_type blue_cones;

   typedef std::vector< ::common_msgs::Cone_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::common_msgs::Cone_<ContainerAllocator> >::other >  _yellow_cones_type;
  _yellow_cones_type yellow_cones;

   typedef std::vector< ::common_msgs::Cone_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::common_msgs::Cone_<ContainerAllocator> >::other >  _orange_cones_type;
  _orange_cones_type orange_cones;





  typedef boost::shared_ptr< ::common_msgs::ConeMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::ConeMap_<ContainerAllocator> const> ConstPtr;

}; // struct ConeMap_

typedef ::common_msgs::ConeMap_<std::allocator<void> > ConeMap;

typedef boost::shared_ptr< ::common_msgs::ConeMap > ConeMapPtr;
typedef boost::shared_ptr< ::common_msgs::ConeMap const> ConeMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::ConeMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::ConeMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'common_msgs': ['/home/aaron/ROS/ros_workspace/src/common/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ConeMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::ConeMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ConeMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::ConeMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ConeMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::ConeMap_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::ConeMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a5312a83690b1beb889fc4f459cf44b";
  }

  static const char* value(const ::common_msgs::ConeMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a5312a83690b1beULL;
  static const uint64_t static_value2 = 0xb889fc4f459cf44bULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::ConeMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/ConeMap";
  }

  static const char* value(const ::common_msgs::ConeMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::ConeMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"common_msgs/Cone[] blue_cones\n"
"common_msgs/Cone[] yellow_cones\n"
"common_msgs/Cone[] orange_cones\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: common_msgs/Cone\n"
"uint8 BLUE=0\n"
"uint8 YELLOW=1\n"
"uint8 ORANGE=2\n"
"\n"
"geometry_msgs/Point position\n"
"uint8 color\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::common_msgs::ConeMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::ConeMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.blue_cones);
      stream.next(m.yellow_cones);
      stream.next(m.orange_cones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConeMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::ConeMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::ConeMap_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "blue_cones[]" << std::endl;
    for (size_t i = 0; i < v.blue_cones.size(); ++i)
    {
      s << indent << "  blue_cones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.blue_cones[i]);
    }
    s << indent << "yellow_cones[]" << std::endl;
    for (size_t i = 0; i < v.yellow_cones.size(); ++i)
    {
      s << indent << "  yellow_cones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.yellow_cones[i]);
    }
    s << indent << "orange_cones[]" << std::endl;
    for (size_t i = 0; i < v.orange_cones.size(); ++i)
    {
      s << indent << "  orange_cones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.orange_cones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_CONEMAP_H
