// Generated by gencpp from file common_msgs/Control.msg
// DO NOT EDIT!


#ifndef COMMON_MSGS_MESSAGE_CONTROL_H
#define COMMON_MSGS_MESSAGE_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace common_msgs
{
template <class ContainerAllocator>
struct Control_
{
  typedef Control_<ContainerAllocator> Type;

  Control_()
    : throttle()
    , braking()
    , steering()  {
    }
  Control_(const ContainerAllocator& _alloc)
    : throttle(_alloc)
    , braking(_alloc)
    , steering(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _throttle_type;
  _throttle_type throttle;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _braking_type;
  _braking_type braking;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::common_msgs::Control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_msgs::Control_<ContainerAllocator> const> ConstPtr;

}; // struct Control_

typedef ::common_msgs::Control_<std::allocator<void> > Control;

typedef boost::shared_ptr< ::common_msgs::Control > ControlPtr;
typedef boost::shared_ptr< ::common_msgs::Control const> ControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_msgs::Control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_msgs::Control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace common_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'common_msgs': ['/home/aaron/ROS/ros_workspace/src/common/common_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_msgs::Control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_msgs::Control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8a968ff18098750e2487c37c9a29dba";
  }

  static const char* value(const ::common_msgs::Control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8a968ff18098750ULL;
  static const uint64_t static_value2 = 0xe2487c37c9a29dbaULL;
};

template<class ContainerAllocator>
struct DataType< ::common_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_msgs/Control";
  }

  static const char* value(const ::common_msgs::Control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_msgs::Control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 throttle\n"
"std_msgs/Float32 braking\n"
"std_msgs/Float32 steering\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::common_msgs::Control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_msgs::Control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.braking);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_msgs::Control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_msgs::Control_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.throttle);
    s << indent << "braking: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.braking);
    s << indent << "steering: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MSGS_MESSAGE_CONTROL_H
