# automatically generated by the FlatBuffers compiler, do not modify

# namespace: InterfaceMessage

import flatbuffers

class Lidar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsLidar(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Lidar()
        x.Init(buf, n + offset)
        return x

    # Lidar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Lidar
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Lidar
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Lidar
    def BytesPerPixel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Lidar
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Lidar
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Lidar
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def LidarStart(builder): builder.StartObject(4)
def LidarAddHeight(builder, height): builder.PrependInt32Slot(0, height, 0)
def LidarAddWidth(builder, width): builder.PrependInt32Slot(1, width, 0)
def LidarAddBytesPerPixel(builder, bytesPerPixel): builder.PrependInt32Slot(2, bytesPerPixel, 0)
def LidarAddData(builder, data): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def LidarStartDataVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def LidarEnd(builder): return builder.EndObject()
