# automatically generated by the FlatBuffers compiler, do not modify

# namespace: InterfaceMessage

import flatbuffers

class Messages(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMessages(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Messages()
        x.Init(buf, n + offset)
        return x

    # Messages
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Messages
    def Messages(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Message import Message
            obj = Message()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Messages
    def MessagesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Messages
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .Message import Message
            obj = Message()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MessagesStart(builder): builder.StartObject(2)
def MessagesAddMessages(builder, messages): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(messages), 0)
def MessagesStartMessagesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def MessagesAddTime(builder, time): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(time), 0)
def MessagesEnd(builder): return builder.EndObject()
