# automatically generated by the FlatBuffers compiler, do not modify

# namespace: InterfaceMessage

class Type(object):
    NONE = 0
    Camera = 1
    Lidar = 2
    GPS = 3
    IMU = 4
    Control = 5
    Time = 6
    Exit = 7

