chrono:
  use_irrlicht:   true
  hostname:       "localhost"
  port:           "8080"

# ros:


# REQUIRED
# sensorX_topic
# sensorX_freq
# sensorX_offset
sensors:
  sensor0:        0 # 0 (camera), 1 (LiDAR), 2 (GPS), 3(IMU)
  sensor0_topic:  camera
  sensor0_freq:   60
  sensor0_offset:    [1, 0, 1,  # x, y, z offset
                0, 1, 0, 0] # Q_from_AngAxis(0, {1, 0, 0}))
  sensor0_width:  1280
  sensor0_height: 720
