// Generated by gencpp from file chrono_launch/Num.msg
// DO NOT EDIT!


#ifndef CHRONO_LAUNCH_MESSAGE_NUM_H
#define CHRONO_LAUNCH_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chrono_launch
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    {
    }
  Num_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::chrono_launch::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chrono_launch::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::chrono_launch::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::chrono_launch::Num > NumPtr;
typedef boost::shared_ptr< ::chrono_launch::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chrono_launch::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chrono_launch::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chrono_launch

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'chrono_launch': ['/home/aaron/ROS/catkin/src/chrono_launch/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chrono_launch::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chrono_launch::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chrono_launch::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chrono_launch::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chrono_launch::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chrono_launch::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chrono_launch::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::chrono_launch::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::chrono_launch::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chrono_launch/Num";
  }

  static const char* value(const ::chrono_launch::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chrono_launch::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::chrono_launch::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chrono_launch::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chrono_launch::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::chrono_launch::Num_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CHRONO_LAUNCH_MESSAGE_NUM_H
