#!/usr/bin/env python
import rospy
import os

def main():
    rospy.init_node("syn_vehicle")

    os.system("/home/aaron/synchrono/build/bin/demo_ROS 8080 ")

if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
