#!/usr/bin/env python
import rospy
import os

def main():
    rospy.init_node("chrono_test")

    os.system("/home/aaron/chrono/build/bin/demo_ROS_tcp_test 8080 ")

if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
