#!/usr/bin/env python
import rospy
import os

def main():
    rospy.init_node("rosbag_record")

    os.system("rosbag record -a -O euler_test")

if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
