#!/usr/bin/env python
import rospy
import sys
import os

def main():
    rospy.init_node("chrono_launch")

    path = "/home/aaron/chrono/build/bin/" + sys.argv[1] + " " + sys.argv[2]

    os.system(path)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("usage: ch_launch <executable to run> <port number>")
    else:
        try:
            main()
        except rospy.ROSInterruptException:
            pass
